[".oh-my-zsh"]
  type = "archive"
  url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zshmarks"]
    type = "archive"
    url = "https://github.com/jocelynmallon/zshmarks/archive/refs/heads/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
